name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        emacs-version:
          - 24.3
          - 24.4
          - 24.5
          - 25.3
          - 26.3
          - 27.2
          - 28.2
          - 29.4
          - snapshot

    steps:
      - uses: actions/checkout@v2

      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs-version }}

      - name: Run tests
        run: make test
